apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      # No security context - major security issue
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          runAsUser: 0  # Running as root - security issue
          allowPrivilegeEscalation: true  # Security issue
          capabilities:
            add:
              - SYS_ADMIN  # Dangerous capability
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        # No resource limits - security issue
        env:
        - name: SECRET_KEY
          value: "hardcoded-secret-key"  # Hardcoded secret - security issue