apiVersion: v2
name: dependency-test
description: A test chart with dependency requirements
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: redis
    version: "17.3.7"
    repository: "https://charts.bitnami.com/bitnami"
  - name: postgresql
    version: "11.9.13"
    repository: "https://charts.bitnami.com/bitnami"